### ISSUE TITLE
对于某些 lerna 管理的项目，可能子 package 中仍然需要添加 eslint 作为依赖，需要弄清楚这个逻辑

### ISSUE THREAD

**Issue by LancelotLewis** [ArcBlock/eslint-config#6]
![image](https://user-images.githubusercontent.com/8749615/128279488-59e5cc88-d870-4ee1-be1c-be4138b38232.png)

**Comment by wangshijun** [comment]
这貌似是因为 npm 查找可执行文件的时候不会往父级目录查找，lerna 下的子包需要显式的依赖，才会有 eslint 之类的 binary 文件

**Comment by wangshijun** [comment]
实际上只是多了个软链

**Comment by LancelotLewis** [comment]
> 这貌似是因为 npm 查找可执行文件的时候不会往父级目录查找，lerna 下的子包需要显式的依赖，才会有 eslint 之类的 binary 文件

等之后抽空可以从这个角度测试一下，然后输出一份相关的文档

**Comment by LancelotLewis** [comment]
> 实际上只是多了个软链

在经过 monorepo 的使用之后理解了这一点，root 层级的包只能在 root 使用，子包中的依赖只能在子包中使用，这是符合逻辑的。

**Comment by LancelotLewis** [comment]
计划在 22 年做一次 pnpm 的使用分享，将涵盖这一点知识。
关于这个点不会输出一个单独的文档了，先 close 掉
