### ISSUE TITLE
eslint react 版本应该包含 react-hooks 插件

### ISSUE THREAD

**Issue by wangshijun** [ArcBlock/eslint-config#9]
https://reactjs.org/docs/hooks-rules.html
这个在我们的 eslint-config 里面有包含么？
如果没有的话，建议加上，帮大家避免低级错误
这也是为啥我们的一些写法在 build 的时候会出错，但是开发环境下没出错
你有空可以更新下我们的 eslint

**Comment by LancelotLewis** [comment]
repo 内包含 eslint-config-base 和 eslint-config 两个 lib
在 eslint-config 中是有 eslint-plugin-react-hooks 的，可能是需要更新一下版本
